name: mdlint

on:
  push:
    paths:
      - "**.md"
  pull_request:
    paths:
      - "**.md"

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Run md linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint md file
        uses: avto-dev/markdown-lint@v1
        with:
          config:
            ".github/lint-rules/md-rules.json"
          args: "**.md"

